# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import hermesdeck_pb2 as hermesdeck__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hermesdeck_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HermesDeckBridgeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessMessage = channel.unary_stream(
                '/hermesdeck.HermesDeckBridge/ProcessMessage',
                request_serializer=hermesdeck__pb2.MessageRequest.SerializeToString,
                response_deserializer=hermesdeck__pb2.MessageResponse.FromString,
                _registered_method=True)
        self.ExecuteTool = channel.unary_unary(
                '/hermesdeck.HermesDeckBridge/ExecuteTool',
                request_serializer=hermesdeck__pb2.ToolRequest.SerializeToString,
                response_deserializer=hermesdeck__pb2.ToolResponse.FromString,
                _registered_method=True)
        self.MemoryOp = channel.unary_unary(
                '/hermesdeck.HermesDeckBridge/MemoryOp',
                request_serializer=hermesdeck__pb2.MemoryRequest.SerializeToString,
                response_deserializer=hermesdeck__pb2.MemoryResponse.FromString,
                _registered_method=True)
        self.SkillOp = channel.unary_unary(
                '/hermesdeck.HermesDeckBridge/SkillOp',
                request_serializer=hermesdeck__pb2.SkillRequest.SerializeToString,
                response_deserializer=hermesdeck__pb2.SkillResponse.FromString,
                _registered_method=True)
        self.RegisterTools = channel.unary_unary(
                '/hermesdeck.HermesDeckBridge/RegisterTools',
                request_serializer=hermesdeck__pb2.ToolRegistry.SerializeToString,
                response_deserializer=hermesdeck__pb2.RegisterAck.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/hermesdeck.HermesDeckBridge/HealthCheck',
                request_serializer=hermesdeck__pb2.HealthRequest.SerializeToString,
                response_deserializer=hermesdeck__pb2.HealthResponse.FromString,
                _registered_method=True)


class HermesDeckBridgeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteTool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MemoryOp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SkillOp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterTools(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HermesDeckBridgeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessMessage': grpc.unary_stream_rpc_method_handler(
                    servicer.ProcessMessage,
                    request_deserializer=hermesdeck__pb2.MessageRequest.FromString,
                    response_serializer=hermesdeck__pb2.MessageResponse.SerializeToString,
            ),
            'ExecuteTool': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteTool,
                    request_deserializer=hermesdeck__pb2.ToolRequest.FromString,
                    response_serializer=hermesdeck__pb2.ToolResponse.SerializeToString,
            ),
            'MemoryOp': grpc.unary_unary_rpc_method_handler(
                    servicer.MemoryOp,
                    request_deserializer=hermesdeck__pb2.MemoryRequest.FromString,
                    response_serializer=hermesdeck__pb2.MemoryResponse.SerializeToString,
            ),
            'SkillOp': grpc.unary_unary_rpc_method_handler(
                    servicer.SkillOp,
                    request_deserializer=hermesdeck__pb2.SkillRequest.FromString,
                    response_serializer=hermesdeck__pb2.SkillResponse.SerializeToString,
            ),
            'RegisterTools': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterTools,
                    request_deserializer=hermesdeck__pb2.ToolRegistry.FromString,
                    response_serializer=hermesdeck__pb2.RegisterAck.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=hermesdeck__pb2.HealthRequest.FromString,
                    response_serializer=hermesdeck__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hermesdeck.HermesDeckBridge', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hermesdeck.HermesDeckBridge', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HermesDeckBridge(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hermesdeck.HermesDeckBridge/ProcessMessage',
            hermesdeck__pb2.MessageRequest.SerializeToString,
            hermesdeck__pb2.MessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hermesdeck.HermesDeckBridge/ExecuteTool',
            hermesdeck__pb2.ToolRequest.SerializeToString,
            hermesdeck__pb2.ToolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MemoryOp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hermesdeck.HermesDeckBridge/MemoryOp',
            hermesdeck__pb2.MemoryRequest.SerializeToString,
            hermesdeck__pb2.MemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SkillOp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hermesdeck.HermesDeckBridge/SkillOp',
            hermesdeck__pb2.SkillRequest.SerializeToString,
            hermesdeck__pb2.SkillResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterTools(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hermesdeck.HermesDeckBridge/RegisterTools',
            hermesdeck__pb2.ToolRegistry.SerializeToString,
            hermesdeck__pb2.RegisterAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hermesdeck.HermesDeckBridge/HealthCheck',
            hermesdeck__pb2.HealthRequest.SerializeToString,
            hermesdeck__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
