// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.6.1
// source: hermesdeck.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	HermesDeckBridge_ProcessMessage_FullMethodName = "/hermesdeck.HermesDeckBridge/ProcessMessage"
	HermesDeckBridge_ExecuteTool_FullMethodName    = "/hermesdeck.HermesDeckBridge/ExecuteTool"
	HermesDeckBridge_MemoryOp_FullMethodName       = "/hermesdeck.HermesDeckBridge/MemoryOp"
	HermesDeckBridge_SkillOp_FullMethodName        = "/hermesdeck.HermesDeckBridge/SkillOp"
	HermesDeckBridge_RegisterTools_FullMethodName  = "/hermesdeck.HermesDeckBridge/RegisterTools"
	HermesDeckBridge_HealthCheck_FullMethodName    = "/hermesdeck.HermesDeckBridge/HealthCheck"
)

// HermesDeckBridgeClient is the client API for HermesDeckBridge service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HermesDeckBridgeClient interface {
	ProcessMessage(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (HermesDeckBridge_ProcessMessageClient, error)
	ExecuteTool(ctx context.Context, in *ToolRequest, opts ...grpc.CallOption) (*ToolResponse, error)
	MemoryOp(ctx context.Context, in *MemoryRequest, opts ...grpc.CallOption) (*MemoryResponse, error)
	SkillOp(ctx context.Context, in *SkillRequest, opts ...grpc.CallOption) (*SkillResponse, error)
	RegisterTools(ctx context.Context, in *ToolRegistry, opts ...grpc.CallOption) (*RegisterAck, error)
	HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type hermesDeckBridgeClient struct {
	cc grpc.ClientConnInterface
}

func NewHermesDeckBridgeClient(cc grpc.ClientConnInterface) HermesDeckBridgeClient {
	return &hermesDeckBridgeClient{cc}
}

func (c *hermesDeckBridgeClient) ProcessMessage(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (HermesDeckBridge_ProcessMessageClient, error) {
	stream, err := c.cc.NewStream(ctx, &HermesDeckBridge_ServiceDesc.Streams[0], HermesDeckBridge_ProcessMessage_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &hermesDeckBridgeProcessMessageClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type HermesDeckBridge_ProcessMessageClient interface {
	Recv() (*MessageResponse, error)
	grpc.ClientStream
}

type hermesDeckBridgeProcessMessageClient struct {
	grpc.ClientStream
}

func (x *hermesDeckBridgeProcessMessageClient) Recv() (*MessageResponse, error) {
	m := new(MessageResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *hermesDeckBridgeClient) ExecuteTool(ctx context.Context, in *ToolRequest, opts ...grpc.CallOption) (*ToolResponse, error) {
	out := new(ToolResponse)
	err := c.cc.Invoke(ctx, HermesDeckBridge_ExecuteTool_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hermesDeckBridgeClient) MemoryOp(ctx context.Context, in *MemoryRequest, opts ...grpc.CallOption) (*MemoryResponse, error) {
	out := new(MemoryResponse)
	err := c.cc.Invoke(ctx, HermesDeckBridge_MemoryOp_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hermesDeckBridgeClient) SkillOp(ctx context.Context, in *SkillRequest, opts ...grpc.CallOption) (*SkillResponse, error) {
	out := new(SkillResponse)
	err := c.cc.Invoke(ctx, HermesDeckBridge_SkillOp_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hermesDeckBridgeClient) RegisterTools(ctx context.Context, in *ToolRegistry, opts ...grpc.CallOption) (*RegisterAck, error) {
	out := new(RegisterAck)
	err := c.cc.Invoke(ctx, HermesDeckBridge_RegisterTools_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hermesDeckBridgeClient) HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, HermesDeckBridge_HealthCheck_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HermesDeckBridgeServer is the server API for HermesDeckBridge service.
// All implementations must embed UnimplementedHermesDeckBridgeServer
// for forward compatibility
type HermesDeckBridgeServer interface {
	ProcessMessage(*MessageRequest, HermesDeckBridge_ProcessMessageServer) error
	ExecuteTool(context.Context, *ToolRequest) (*ToolResponse, error)
	MemoryOp(context.Context, *MemoryRequest) (*MemoryResponse, error)
	SkillOp(context.Context, *SkillRequest) (*SkillResponse, error)
	RegisterTools(context.Context, *ToolRegistry) (*RegisterAck, error)
	HealthCheck(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedHermesDeckBridgeServer()
}

// UnimplementedHermesDeckBridgeServer must be embedded to have forward compatible implementations.
type UnimplementedHermesDeckBridgeServer struct {
}

func (UnimplementedHermesDeckBridgeServer) ProcessMessage(*MessageRequest, HermesDeckBridge_ProcessMessageServer) error {
	return status.Errorf(codes.Unimplemented, "method ProcessMessage not implemented")
}
func (UnimplementedHermesDeckBridgeServer) ExecuteTool(context.Context, *ToolRequest) (*ToolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteTool not implemented")
}
func (UnimplementedHermesDeckBridgeServer) MemoryOp(context.Context, *MemoryRequest) (*MemoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MemoryOp not implemented")
}
func (UnimplementedHermesDeckBridgeServer) SkillOp(context.Context, *SkillRequest) (*SkillResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SkillOp not implemented")
}
func (UnimplementedHermesDeckBridgeServer) RegisterTools(context.Context, *ToolRegistry) (*RegisterAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterTools not implemented")
}
func (UnimplementedHermesDeckBridgeServer) HealthCheck(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedHermesDeckBridgeServer) mustEmbedUnimplementedHermesDeckBridgeServer() {}

// UnsafeHermesDeckBridgeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HermesDeckBridgeServer will
// result in compilation errors.
type UnsafeHermesDeckBridgeServer interface {
	mustEmbedUnimplementedHermesDeckBridgeServer()
}

func RegisterHermesDeckBridgeServer(s grpc.ServiceRegistrar, srv HermesDeckBridgeServer) {
	s.RegisterService(&HermesDeckBridge_ServiceDesc, srv)
}

func _HermesDeckBridge_ProcessMessage_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MessageRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HermesDeckBridgeServer).ProcessMessage(m, &hermesDeckBridgeProcessMessageServer{stream})
}

type HermesDeckBridge_ProcessMessageServer interface {
	Send(*MessageResponse) error
	grpc.ServerStream
}

type hermesDeckBridgeProcessMessageServer struct {
	grpc.ServerStream
}

func (x *hermesDeckBridgeProcessMessageServer) Send(m *MessageResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _HermesDeckBridge_ExecuteTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HermesDeckBridgeServer).ExecuteTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HermesDeckBridge_ExecuteTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HermesDeckBridgeServer).ExecuteTool(ctx, req.(*ToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HermesDeckBridge_MemoryOp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MemoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HermesDeckBridgeServer).MemoryOp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HermesDeckBridge_MemoryOp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HermesDeckBridgeServer).MemoryOp(ctx, req.(*MemoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HermesDeckBridge_SkillOp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HermesDeckBridgeServer).SkillOp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HermesDeckBridge_SkillOp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HermesDeckBridgeServer).SkillOp(ctx, req.(*SkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HermesDeckBridge_RegisterTools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToolRegistry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HermesDeckBridgeServer).RegisterTools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HermesDeckBridge_RegisterTools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HermesDeckBridgeServer).RegisterTools(ctx, req.(*ToolRegistry))
	}
	return interceptor(ctx, in, info, handler)
}

func _HermesDeckBridge_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HermesDeckBridgeServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HermesDeckBridge_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HermesDeckBridgeServer).HealthCheck(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HermesDeckBridge_ServiceDesc is the grpc.ServiceDesc for HermesDeckBridge service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HermesDeckBridge_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hermesdeck.HermesDeckBridge",
	HandlerType: (*HermesDeckBridgeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteTool",
			Handler:    _HermesDeckBridge_ExecuteTool_Handler,
		},
		{
			MethodName: "MemoryOp",
			Handler:    _HermesDeckBridge_MemoryOp_Handler,
		},
		{
			MethodName: "SkillOp",
			Handler:    _HermesDeckBridge_SkillOp_Handler,
		},
		{
			MethodName: "RegisterTools",
			Handler:    _HermesDeckBridge_RegisterTools_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _HermesDeckBridge_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ProcessMessage",
			Handler:       _HermesDeckBridge_ProcessMessage_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "hermesdeck.proto",
}
